//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense_entity
    {
        public int expense_entity_id { get; set; }
        public string expense_entity_name { get; set; }
    }
}
