//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<int> cell_phone { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> country_origin { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string email { get; set; }
        public Nullable<int> state { get; set; }
        public int owner_id { get; set; }
        public Nullable<int> dni { get; set; }
        public string dni_vr { get; set; }
    }
}
