//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CONDOMINIOEntities : DbContext
    {
        public CONDOMINIOEntities()
            : base("name=CONDOMINIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<owner> owner { get; set; }
        public virtual DbSet<period> period { get; set; }
        public virtual DbSet<expense> expenses { get; set; }
        public virtual DbSet<expense_concept> expense_concept { get; set; }
        public virtual DbSet<expense_entity> expense_entity { get; set; }
        public virtual DbSet<vw_month_state_list> vw_month_state_list { get; set; }
        public virtual DbSet<income_concept> income_concept { get; set; }
        public virtual DbSet<income> incomes { get; set; }
    
        public virtual ObjectResult<sp_c_summary_by_period_Result> sp_c_summary_by_period(Nullable<int> period_id)
        {
            var period_idParameter = period_id.HasValue ?
                new ObjectParameter("period_id", period_id) :
                new ObjectParameter("period_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_c_summary_by_period_Result>("sp_c_summary_by_period", period_idParameter);
        }
    
        public virtual ObjectResult<sp_c_property_Result> sp_c_property()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_c_property_Result>("sp_c_property");
        }
    
        public virtual ObjectResult<sp_c_month_state_Result> sp_c_month_state(Nullable<int> period_id)
        {
            var period_idParameter = period_id.HasValue ?
                new ObjectParameter("period_id", period_id) :
                new ObjectParameter("period_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_c_month_state_Result>("sp_c_month_state", period_idParameter);
        }
    }
}
