//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_month_state_list
    {
        public int month_state_id { get; set; }
        public string period_desc { get; set; }
        public Nullable<System.DateTime> generation_date { get; set; }
        public Nullable<int> total_records { get; set; }
        public Nullable<decimal> total_expenses { get; set; }
        public Nullable<decimal> total_incomes { get; set; }
        public Nullable<decimal> total_net { get; set; }
    }
}
